# Generated by Django 6.0.5 on 2026-06-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investigador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("resumo", models.TextField()),
                ("data_inicio", models.DateField()),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos_coordenados",
                        to="projetos.investigador",
                    ),
                ),
                (
                    "investigadores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projetos_associados",
                        to="projetos.investigador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entregavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("data_entrega", models.DateField()),
                ("link", models.URLField()),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregaveis",
                        to="projetos.projeto",
                    ),
                ),
            ],
        ),
    ]
